### ISSUE TITLE
IOS 8 : xCode 6 : Unknown type BOOL Error

### ISSUE THREAD

**Issue by wm-j-ray** [balram3429/btSimplePopUp#5]
On line 14 of simplePopUp.m, I keep getting this error....

```
 typedef void (^completion)(BOOL success);
```

any idea what I can do to fix it?  I've sourced out your h and m's into a test project. I changed the above line to:

```
typedef void (^completion)();
```

and the app compiles and runs without error.  Question:  Did I break something I don't know about by modifying the block?

Thanx in Advance

**Comment by toftof** [comment]
Any updates?

**Comment by ildsarria** [comment]
I had the very same issue, and found that I just had to include these two imports:
#import <QuartzCore/QuartzCore.h>
#import <Accelerate/Accelerate.h>
